### PR TITLE
This pull request includes updates to the main CSS file to improve the usability of our web application's major components. Changes have been made to enhance the responsiveness, color scheme, and overall layout to provide a more intuitive and user-friendly experience.

### PR DESCRIPTION
**Pull request by RitaIshimwe**

### CODE REVIEW

**Review by taqwaaosman — APPROVED** [review]
Sounds good. I’ll have to double check my css to make sure there is consistent formatting.

**Comment by taqwaaosman** [comment]
Just realized that you were supposed to merge the pull request 😭 Sorry about that

**Comment by taqwaaosman** [comment]
I didn’t realize I was doing that as approved the request

**Comment by RitaIshimwe** [comment]
No worries at all! It's completely okay.

**Pull request merged**
